"""tenants leases

Revision ID: bfe48033a430
Revises: ecfc4227a8b6
Create Date: 2026-10-03 07:53:36.989624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfe48033a430'
down_revision: Union[str, Sequence[str], None] = 'ecfc4227a8b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('national_id', sa.String(length=64), nullable=True),
    sa.Column('emergency_contact', sa.String(length=160), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'phone')
    )
    op.create_index(op.f('ix_tenants_property_id'), 'tenants', ['property_id'], unique=False)
    op.create_table('leases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('monthly_rent', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('terminated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leases_property_id'), 'leases', ['property_id'], unique=False)
    op.create_index(op.f('ix_leases_tenant_id'), 'leases', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_leases_unit_id'), 'leases', ['unit_id'], unique=False)
    op.create_index('uq_leases_one_open_per_unit', 'leases', ['unit_id'], unique=True, sqlite_where=sa.text('is_active'), postgresql_where=sa.text('is_active'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_leases_one_open_per_unit', table_name='leases', sqlite_where=sa.text('is_active'), postgresql_where=sa.text('is_active'))
    op.drop_index(op.f('ix_leases_unit_id'), table_name='leases')
    op.drop_index(op.f('ix_leases_tenant_id'), table_name='leases')
    op.drop_index(op.f('ix_leases_property_id'), table_name='leases')
    op.drop_table('leases')
    op.drop_index(op.f('ix_tenants_property_id'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
